[workspace]
members = [
    "crates/yaqmc-core",
    "crates/yaqmc-protocol",
    "crates/yaqmc-provider-api",
    "crates/yaqmc-provider-qqmusic",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "GPL-3.0-or-later"
rust-version = "1.88"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
