export {
  ANDROID_HOST_CAPABILITIES,
  DESKTOP_HOST_CAPABILITIES,
  FAKE_HOST_CAPABILITIES,
  defaultHostCapabilities,
  type HostBridge,
  type HostCapabilities,
  type HostClipboardBridge,
  type HostDialogBridge,
  type HostKind,
  type HostOpenFileKind,
  type HostSaveFileKind,
  type HostShellBridge,
  type HostWindowBridge,
  type HostNativeShareBridge,
  type HostNativeShareRequest,
  type HostShareBridge,
  type HostShareRequest,
  type InvokeArgs,
  type WindowRole,
} from './bridge';
export { CoreUnavailableError, READY_QUEUE_TIMEOUT_MS, YaqmcClient } from './client';
export {
  dispatchPlayerCommand,
  setPlayerCommandAdapter,
  type PlayerCommand,
  type PlayerCommandAdapter,
} from './player-command-adapter';
export { createElectronBridge, type ElectronRendererApi } from './bridges/electron';
export {
  createAndroidBridge,
  readCapacitorAndroidApi,
  type AndroidRendererApi,
} from './bridges/android';
export { createFakeBridge, type FakeCatalog } from './bridges/fake';
export {
  CHANNEL_ACCOUNT_CHANGED,
  CHANNEL_API_EVENT,
  CHANNEL_APP_OPEN_CATALOG_SONG,
  CHANNEL_APP_OPEN_SETTINGS,
  CHANNEL_CORE_LOG,
  CHANNEL_HOST_COMMAND,
  CHANNEL_HOST_CORE_STATUS,
  CHANNEL_HOST_UPDATE,
  CHANNEL_LYRICS_DOCUMENT,
  CHANNEL_LYRICS_PROJECTION,
  CHANNEL_LYRICS_SURFACE_CLOSED,
  CHANNEL_LYRICS_SURFACE_INTERACTION,
  CHANNEL_PLAYER_SNAPSHOT,
  CHANNEL_PLUGIN_CHANGED,
  CHANNEL_PREFERENCES_CHANGED,
  CORE_EVENT_CHANNELS,
  HOST_EVENT_CHANNELS,
  type ChannelName,
  type ChannelPayload,
  type CoreChannelName,
  type CoreStatus,
  type CoreStatusPayload,
  type HostChannelName,
  type OpenCatalogSongPayload,
  type UpdatePayload,
  type UpdateState,
} from './protocol/events';
export {
  METHOD_NAMES,
  MIGRATED_METHOD_NAMES,
  PROTOCOL_ONLY_METHODS,
  type MigratedMethodName,
  type MethodName,
  type MethodParams,
  type MethodResult,
  type ParamsOf,
  type ProtocolOnlyMethodName,
  type ResultOf,
} from './protocol/methods';
export {
  DEFAULT_METHOD_PAYLOAD_BYTES,
  ERROR_CODES,
  FRAME_HARD_CAP_BYTES,
  HANDSHAKE_TIMEOUT_MS,
  PROTOCOL_VERSION,
  SHUTDOWN_TIMEOUT_MS,
  type CoreError,
  type CoreIdentity,
  type CoreMessage,
  type ErrorCode,
  type HostIdentity,
  type PlatformAttach,
  type PlatformKind,
  type DisplayBackend,
  type ResponseBody,
  type ShutdownReason,
} from './protocol/types';
export type * from './protocol/dto';
